# Generated by Django 4.2 on 2025-11-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerecord',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
