# Generated by Django 4.2 on 2025-11-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_alter_imagerecord_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerecord',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='result_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imagerecord',
            name='image_url',
            field=models.CharField(max_length=1000),
        ),
    ]
